### ISSUE TITLE
Assalomu alaykum! Shu saytda orqa fondagi border 2 ta bo'lib qolgan va chap tarafdan ozroq joy qolib ketgan shuni to'g'irlab qo'ysak yaxshi bo'lar edi!

### ISSUE THREAD

**Issue by shakhbozbekusmonov** [orifjonov-abbosbek/scoot#1]
![image](https://user-images.githubusercontent.com/83509440/204709315-dc371bca-5839-46da-9035-50e53ac997f6.png)

**Comment by orifjonov-abbosbek** [comment]
![Screenshot from 2022-11-30 10-14-44](https://user-images.githubusercontent.com/116246851/204713330-f186f7eb-dac0-405e-a30e-555c09ce261c.png)


fixed
