### ISSUE TITLE
Ushbu bo'limda, rasm va contentni o'rab turgan wrapperga justify-content:  space-between; berib qo'ysak yaxshi bo'lar edi!

### ISSUE THREAD

**Issue by shakhbozbekusmonov** [orifjonov-abbosbek/scoot#4]
![image](https://user-images.githubusercontent.com/83509440/204710871-d9eb638b-e110-49ae-af38-659767a46e0e.png)

**Comment by orifjonov-abbosbek** [comment]
![Screenshot from 2022-11-30 10-17-45](https://user-images.githubusercontent.com/116246851/204713717-9b57159c-540a-44cb-b5ac-c3fc205312c5.png)
justify-content: space-between; berilib background holati to'g'irlandi.


fixed !
